version: '3.9'
services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - "9090:9090"
        network_mode: "host"
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    grafana:
        image: grafana/grafana
        container_name: grafana
        network_mode: "host"
        ports:
            - "3000:3000"
        volumes:
            - ./grafana.ini:/etc/grafana/grafana.ini
            - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
        depends_on:
            - prometheus
